os: linux
sudo: false
language: node_js
node_js: 
  - "10"
dist: trusty
cache: {
  yarn: true,
  "directories": [
      "node_modules"
  ]
}
install: yarn
script: "yarn run lint"

branches:
  only:
    - master
    - develop

after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success $WEBHOOK
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK